#!/bin/bash
# format frappe:latest, erpnext:stable
TAG=$(echo ${IMAGE_NAME##*/})

# format latest, latest-ubuntu, latest-alpine
IFS=':' read -r -a TAG_VALUES <<< "$TAG"
VERSION="${TAG_VALUES[0]:-latest}"
FLAVOR="${TAG_VALUES[1]:-ubuntu}"

CONTEXT

docker build \
  --build-arg BRANCH=$BRANCH \
  -t $IMAGE_NAME .
